function testcase() {
  Log.Message("Existing for re-run fail cases!")
}